### ISSUE TITLE
praat-textgrids does not run with mac Os

### ISSUE THREAD

**Issue by maxime-fily** [Legisign/Praat-textgrids#7]
I bumped into an odd situation trying a script using praat-textgrids on another python distro. The program returns the following error message:
>Traceback (most recent call last):
>  File "TXTGRD2XML_input-txt.py", line 161, in <module>
>    grid.tier_to_csv('numitem', fcsv)
>  File "/Users/bibi/anaconda3/lib/python3.6/site-packages/textgrids/__init__.py", line 439, in tier_to_csv
>    csvfile.write('\n'.join(self[tier_name].to_csv()))
>  File "/Users/bibi/anaconda3/lib/python3.6/site-packages/textgrids/__init__.py", line 137, in to_csv
>    return ['"{}";{};{}'.format(t, xb, xe) for t, xb, xe in self]
>  File "/Users/bibi/anaconda3/lib/python3.6/site-packages/textgrids/__init__.py", line 137, in <listcomp>
>    return ['"{}";{};{}'.format(t, xb, xe) for t, xb, xe in self]
>TypeError: 'Interval' object is not iterable

I use 
Anaconda 1.6.11
Spyder 3.2.4
MacOs Big Sur
python 3.6.4

Enclosed : my program and input files used (which works as is on a linux RedHat distro with python 3.9)
[MWE_macos_issue.zip](https://github.com/Legisign/Praat-textgrids/files/6592207/MWE_macos_issue.zip)
 work as is on a linux RedHat distro with python 3.9)

**Comment by maxime-fily** [comment]
The problem with the production version (1.3.1) had been solved in the development version (1.4.0.dev6), the issue declared was therefore unnecessary and redundant. I would suggest that this issue be removed, and also that the development version be put in production whenever deemed possible.
