### ISSUE TITLE
pip installation issues on Windows

### ISSUE THREAD

**Issue by RoyAlderton** [Legisign/Praat-textgrids#9]
In the last few days I have tried to install the package using pip on several different Windows computers, but the same error message has appeared each time - see below. The source of the error appears to be to do with decoding Unicode. This does not appear to be an issue on Linux.

```
> C:\Users\username>pip install praat-textgrids
Collecting praat-textgrids
  Using cached praat-textgrids-1.3.1.tar.gz (12 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\username\AppData\Local\Temp\pip-install-4g5tr4e2\praat-textgrids_eb84bfb1548c468b8a35323f37fc4b0c\setup.py", line 29, in <module>
          long_description = readme.read()
        File "c:\users\username\appdata\local\programs\python\python39\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3159: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by RoyAlderton** [comment]
I realise that this issue is the same as number 3, which is already reported. I will now close the issue.
